name = "gip"
version = "1.0.0"

description = "Process ip's in js and erlang via gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "BradBot1", repo = "gleam_gip" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript]
typescript_declarations = true
runtime = "node"
